pub mod device;
pub use device::Device;
pub use device::Action as DeviceAction;
pub use device::Speed as DeviceSpeed;
pub use device::Notification as DeviceNotification;
pub use device::InterfaceConnectionType as DeviceInterfaceConnectionType;
// pub use device::InterfaceType as DeviceInterfaceType;
// pub use device::Notification as DeviceNotification;
// pub use device::NotificationCallback as DeviceNotificationCallback;
// pub use device::NotificationCallbackInfo as DeviceNotificationCallbackInfo;
